default_stages: [pre-commit, pre-push]
repos:
  - repo: local
    hooks:
      - id: bun
        name: bun
        entry: bun test
        always_run: true
        pass_filenames: false
        language: system
        verbose: false